fix(next-tag): fix regression when calling svu current with multiple tags
Signed-off-by: Frederic BIDON <fredbi@yahoo.com>

diff --git a/ci-jobs/next-tag/action.yml b/ci-jobs/next-tag/action.yml
--- a/ci-jobs/next-tag/action.yml
+++ b/ci-jobs/next-tag/action.yml
@@ -52,7 +52,7 @@ runs:
       run: |
         # determine next tag to push
         NEXT_TAG=""
-        CURRENT=$(svu current)
+        CURRENT=$(svu current||true)   # NOTE: fails when multiple tags - we just want to catch the case when no tag exists
         if [[ "${CURRENT}" == "v0.0.0" ]] ; then
           # never been tagged before: initialize v0.0.1
           NEXT_TAG="v0.0.1"
